import { getEslintConfig } from "eslint-config-setup";

// React site plus Node-side build scripts (scripts/, vite and react-router config).
const config = await getEslintConfig({ react: true, node: true, oxlint: true });

config.unshift({
  ignores: [
    "**/dist/**",
    "build/**",
    ".react-router/**",
    "coverage/**",
    "node_modules/**",
    "pnpm-lock.yaml",
    "**/*.json",
    "**/*.md",
    // Generated by Ardo, never hand-edited (see AGENTS.md).
    "app/routes.ts",
  ],
});

// Deliberate overrides on top of the org config.
config.push(
  {
    // The page is one long, flat composition of the design system's sections
    // (DESIGN.md); splitting it into helper components to satisfy a line budget
    // would hide the document structure the comp is reviewed against.
    files: ["app/**/*.tsx"],
    rules: {
      complexity: "off",
      "max-lines": "off",
      "max-lines-per-function": "off",
      // Route modules export `meta`, `handle`, and loaders next to the component.
      "react-refresh/only-export-components": "off",
    },
  },
  {
    // React Router owns this signature.
    files: ["app/entry.server.tsx"],
    rules: { "max-params": "off" },
  },
);

export default config;
